app:
  messages:
    color: BLACK
  bot:
    token: "MTE0NDc2OTU1MzUwMzYxNzEzNA.G-1fqE.A3Tt6xLxGlPsFWVyNHY7rfosBkpMRCz806dqWg"
spring:
  data:
    mongodb:
      uri: mongodb://localhost:30001/mongod
